apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: welcome-pipeline-ops
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    #repoURL: http://gitea.default.svc.cluster.local:3000/gitea/kubernetes-secrets-source.git
    repoURL: https://github.com/genekuo-org/gitops-demo.git
    targetRevision: HEAD
    path: welcome-message-gitops/pipelines
  destination:
    server: https://kubernetes.default.svc
    namespace: default
